<div id="tituloPagina">
Empregados cadastrados no sistema
</div>
<br><div id="barraBotoes">
	<button id="novo">Novo...</button>
</div>
<table class="hover" id="consulta">
	<thead>
		<tr>
			<th style="text-align: left;">Matricula</th>
			<th style="text-align: left;">Nome</th>
			<th style="text-align: left;">CPF</th>
			<th width="90" class="center">Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($empregados as $empregado):?>
		<tr>
			<td id="matricula"><?php echo $this->escapeHtml($empregado->getMatricula());?></td>
			<td id="nome"><?php echo $this->escapeHtml($empregado->getNome());?></td>
			<td id="cpf"><?php
    
echo $this->escapeHtml(substr($empregado->getCpf(), 0, 3) . "." . substr($empregado->getCpf(), 3, 3) . "." . substr($empregado->getCpf(), 6, 3) . "-" . substr($empregado->getCpf(), 9, 2));
    ?></td>
			<td style="text-align: center"><a
				href="/application/empregado/save/matricula/<?php echo $empregado->getMatricula();?>"><span
					title="Editar" class="ui-icon ui-icon-pencil" /></a> <a
				href="/application/empregado/delete/matricula/<?php echo $empregado->getMatricula();?>"
				id="excluir"><span title="Excluir" class="ui-icon ui-icon-trash" /></a>
		
		</tr>
<?php endforeach;?>



</table>
<div id="dialog-form" title="Confirmar exclusão">
	<p id="texto" />
</div>
<script>
$("#novo").button({
	icons: {
		primary: "ui-icon-plus",
	},
text: true,
});
$("#novo").click(function(e) {
	e.preventDefault();
	window.location ="/application/empregado/save";
});
$("input[type=submit], a" ).button();
	$('#consulta').dataTable({
    	"bLengthChange": false,
    	"aaSorting": [[1, "asc"]],
    	"iDisplayLength": 17,
     });
	$("a#excluir").on("click", function(e) {
        e.preventDefault();
        var link = $(this).attr('href');
        var nome = $(this).closest('tr').find('#nome').text();
        $("#texto").html("Deseja realmente excluir '"+nome+"'?");
        $("#dialog-form").data("link", link);
        $("#dialog-form").dialog("open");
    });
	 $( "#dialog-form" ).dialog({
			dialogClass: 'no-close',
	        autoOpen: false,
	        resizable: false,
	        draggable: false,
	        height: 200,
	        width: 300,
	        modal: true,
	        buttons: {
	     		"Não": function() {
	         		$(this).dialog("close");
	         	},
	     		"Sim": function() {
	        		var link = $(this).data("link");
	            	window.location = link;
	           }
		}
    });
   </script>