<?php
use Zend\Form\Element\Submit;
?>
<br />
<br />
<br />
<br />
<div id="tituloPagina">Cadastro de Curso</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Curso</a></li>
	</ul>
	<div id="dados">
<?php
echo $this->form()->openTag($form);
echo $this->formInput($form->get('id'));

echo $this->formLabel($form->get('descricao')) . "<br />";
echo $this->formInput($form->get('descricao')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('descricao')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('cargaHoraria')) . "<br />";
echo $this->formInput($form->get('cargaHoraria')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('cargaHoraria')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('cursoTipo')) . "<br />";
echo $this->formSelect($form->get('cursoTipo')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('cursoTipo')) . "<descricao />";
?></div><?php

echo $this->formInput($form->get("submit"));
echo $this->form()->closeTag();
?>
</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<script>
$(document).ready(function(){
	  $('#cargaHoraria').mask('00000');
	});

$("#submit").hide();
$("#cancelar").button({
    icons: {
        primary: "ui-icon-close",
    },
    text: true,
});
$("#salvar").button({
	icons: {
		primary: "ui-icon-disk",
	},
text: true,
});
$("#cancelar").click(function(e) {
	e.preventDefault();
	window.location ="/application/curso";
});
$("#salvar").click(function(e) {
	e.preventDefault();
	$("#submit").click();
});
$("#tabs").tabs();

</script>