<div id="tituloPagina">Cadastro de Conhecimento</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Conhecimento</a></li>
	</ul>
	<div id="dados">
		<?php
echo $this->form()->openTag($form);
// echo $this->formCollection($form);
echo $this->formInput($form->get('id'));

echo $this->formLabel($form->get('titulo')) . "<br />";
echo $this->formInput($form->get('titulo')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('titulo')) . "<descricao />";
?></div><?php

echo $this->formSubmit($form->get('submit')) . "<br />";
?>
		<table id="listaEmpregado">
			<thead>
				<tr>
					<th>Matrícula</th>
					<th>Nome</th>
					<th>Opções</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->empregados as $empregado):?>
			<tr>
					<td><input id="empregado" name="matricula[]"
						value="<?php echo $empregado->getMatricula();?>" type="hidden"><?php echo $this->escapeHtml($empregado->getMatricula());?></td>
					<td><?php echo $this->escapeHtml($empregado->getNome());?></td>
					<td><button
							id="excluirEmpregado_<?php echo $empregado->getMatricula();?>">Remover
							Empregado</button></td>
				</tr>
			<?php endforeach;?>		
			</tbody>
		</table>
		<?php
echo $this->form()->closeTag();
?>
	<br>
		<button id="adicionarParticipantes">Adicionar Empregados</button>
	</div>
</div>
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<div id="modal-participantes" title="Adicionar Empregados"
	class="ui-widget">
	<div id="empregados"></div>
</div>