<div id="tituloPagina">
	<h1>Cargos cadastrados no sistema</h1>
</div>
<br>
<div id="barraBotoes">
	<button id="novo">Novo...</button>
</div>
<br><p>
<table class="hover" id="consulta">
	<thead>
		<tr>
			<th style="text-align: left;">Descricao</th>
			<th width="90" class="center">Opções</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($cargos as $cargo):?>
		<tr>
			<td id="descricao"><?php echo $this->escapeHtml($cargo->getDescricao());?></td>

			<td style="text-align: center"><a
				href="/application/cargo/save/id/<?php echo $cargo->getId();?>"><span
					title="Editar" class="ui-icon ui-icon-pencil" /></a> <a
				href="/application/cargo/delete/id/<?php echo $cargo->getId();?>"
				id="excluir"><span title="Excluir" class="ui-icon ui-icon-trash" /></a>
		</tr>
<?php endforeach;?>
</table>
<div id="dialog-form" title="Confirmar exclusão">
	<p id="texto" />
</div>
<script>
$("input[type=submit], a" ).button();
	$("#novo").button({
		icons: {
			primary: "ui-icon-plus",
		},
	text: true,
	});
	
	$("#novo").click(function(e) {
		e.preventDefault();
		window.location ="/application/cargo/save";
});
    $("a#excluir").on("click", function(e) {
        e.preventDefault();
        var link = $(this).attr('href');
        var descricao = $(this).closest('tr').find('#descricao').text();
        $("#texto").html("Deseja realmente excluir '"+descricao+"'?");
        $("#dialog-form").data("link", link);
        $("#dialog-form").dialog("open");
    });
    $( "#dialog-form" ).dialog({
		dialogClass: 'no-close',
        autoOpen: false,
        resizable: false,
        draggable: false,
        height: 200,
        width: 300,
        modal: true,
        buttons: {
     		"Não": function() {
         		$(this).dialog("close");
         	},
     		"Sim": function() {
        		var link = $(this).data("link");
            	window.location = link;
           }
	}
    });
    $('#consulta').dataTable( {
        "bLengthChange": false,
        "pageLength": 18,
        "aaSorting": [[ 1, "desc" ]]
	});
     
	</script>