<?php
use Zend\Form\Element\Submit;
?>
<br />
<br />
<br />
<br />
<div id="tituloPagina">Cadastro de Instituições</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Instituição</a></li>
	</ul>
	<div id="dados">
<?php
echo $this->form()->openTag($form);
echo $this->formInput($form->get('id'));

echo $this->formLabel($form->get('cnpj')) . "<br />";
echo $this->formInput($form->get('cnpj')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('cnpj')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('razaoSocial')) . "<br />";
echo $this->formInput($form->get('razaoSocial')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('razaoSocial')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('cep')) . "<br />";
echo $this->formInput($form->get('cep')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('cep')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('endereco')) . "<br />";
echo $this->formInput($form->get('endereco')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('endereco')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('localizacao')) . "<br />";
echo $this->formInput($form->get('localizacao')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('localizacao')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('bairro')) . "<br />";
echo $this->formInput($form->get('bairro')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('bairro')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('telefone')) . "<br />";
echo $this->formInput($form->get('telefone')) . "<br />";
echo $this->formElementErrors($form->get('telefone')) . "<br />";

echo $this->formLabel($form->get('email')) . "<br />";
echo $this->formInput($form->get('email')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('email')) . "<descricao />";
?></div><?php

echo $this->formSubmit($form->get('submit')) . "<br />";
echo $this->form()->closeTag();
?>
</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<script>
$("#submit").hide();
$('#cnpj').mask('00.000.000/0000-00');
$('#cep').mask('00000-000');
$('#telefone').setMask("(99)9999-99999").ready(function(event) {
    var target, phone, element;
    target = (event.currentTarget) ? event.currentTarget : event.srcElement;
    phone = target.value.replace(/\D/g, '');
    element = $(target);
    element.unsetMask();
    if(phone.length > 10) {
        element.setMask("(99) 99999-9999");
    } else {
        element.setMask("(99) 9999-9999");
    }
});
$("#salvar").button({
	icons: {
		primary: "ui-icon-disk",
	},
text: true,
});
$("#cancelar").button({
	icons: {
		primary: "ui-icon-close",
	},
text: true,
});
$("#cancelar").click(function(e) {
	e.preventDefault();
	window.location ="/application/instituicao";
});
$("#salvar").click(function(e) {
	e.preventDefault();
	$("#submit").click();
	
});
$("#tabs").tabs();
</script>