<?php
use Zend\Form\Element\Submit;
?>
<br />
<br />
<br />
<br />
<div id="tituloPagina">Cadastro de Professor</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Professor</a></li>
	</ul>
	<div id="dados">
<?php
echo $this->form()->openTag($form);
echo $this->formInput($form->get('id'));

echo $this->formLabel($form->get('nome')) . "<br />";
echo $this->formInput($form->get('nome')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('nome')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('email')) . "<br />";
echo $this->formInput($form->get('email')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('email')) . "<descricao />";
?></div><?php

echo $this->formLabel($form->get('telefone')) . "<br />";
echo $this->formInput($form->get('telefone')) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors($form->get('telefone')) . "<descricao />";
?></div><?php

echo $this->formInput($form->get("submit"));
echo $this->form()->closeTag();
?>
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>
<script>
	$("#instituicao").selectmenu();
 	$("#submit").hide();
	$("#cancelar").button({
		icons: {
			primary: "ui-icon-close",
		},
	text: true,
	});
	$(document).ready(function(){
	  $('#telefone').mask('(00)0000-00000');
	});
	$("#salvar").button({
		icons: {
			primary: "ui-icon-disk",
		},
	text: true,
	});
	$("#cancelar").click(function(e) {
		e.preventDefault();
		window.location ="/application/professor";
	});
	$("#salvar").click(function(e) {
		e.preventDefault();
		$("#submit").click();
	});
	$("#tabs").tabs();
	
</script>