<?php
use Zend\Form\Element\Submit;
?>
<div id="tituloPagina">Cadastro de Setor</div>
<div id="tabs">
	<ul>
		<li><a href="#dados">Setor</a></li>
	</ul>
	<div id="dados">
<?php
echo $this->form ()->openTag ( $form );
echo $this->formInput ( $form->get ( 'id' ) );

echo $this->formLabel ( $form->get ( 'nome' ) ) . "<br />";
echo $this->formInput ( $form->get ( 'nome' ) ) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors ( $form->get ( 'nome' ) ) . "<descricao />";
?></div><?php

echo $this->formLabel ( $form->get ( 'gerente' ) ) . "<br />";
echo $this->formSelect ( $form->get ( 'gerente' ) ) . "<br />";
?><div style="width: 800px; font-size: 20px; color: red; height: 25px;"><?php
echo $this->formElementErrors ( $form->get ( 'gerente' ) ) . "<descricao />";
?></div><?php

echo $this->formSubmit ( $form->get ( 'submit' ) ) . "<br />";
?>
		<?php
		echo $this->form ()->closeTag ();
		?>		
	</div>
</div>
<div id="barraBotoes">
	<button id="cancelar">Cancelar</button>
	<button id="salvar">Salvar</button>
</div>